import { Inter } from "next/font/google";
import { Monoton } from "next/font/google";
import "./globals.css";
import { NavBar } from "./components/nav/nav";
import Footer from "./components/footer/footer"


const inter = Inter({ 
  subsets: ["latin"], 
  display: 'swap', 
  variable: '--font-inter',
 });

 const mono = Monoton({
  weight: '400',
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-mono',
 })


export const metadata = {
  title: "OctaGroove Spotify",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {

  return (
    <html lang="en" className={`${inter.variable} ${mono.variable}`}>
      <body className="min-h-screen">
        <NavBar />
        <main className=" ">
          {children}
        </main>
        <Footer />
        </body>
    </html>
  )
}
