import { Inter } from "next/font/google";
import "./globals.css";
import { NavBar } from "./components/nav";

const inter = Inter({ 
  subsets: ["latin"], 
  display: 'swap', 
  variable: '--font-inter',
 });

export const metadata = {
  title: "OctoGroove Spotify",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${inter.variable}`}>
      <body className="min-h-screen">
        <NavBar />
        <main>
        {children}
        </main>
        </body>
    </html>
  )
}
